services:
  mongo-express:
    image: mongo-express:1.0.2-20
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: host.docker.internal
      ME_CONFIG_MONGODB_PORT: 27017
    restart: unless-stopped


